name: metaeuk 
description: MetaEuk is a toolkit for large-scale gene discovery and annotation in eukaryotes from metagenomes.
url: https://github.com/soedinglab/metaeuk
authors:
  - Rodolfo Brandão Dias Ferreira
  - Artur Rafael de Oliveira Gomes
input:
  - fasta: FASTA file with the query sequences (e.g. contigs).
  - db: Target database (FASTA file or MetaEuk/MMseqs2 database).
output:
  - fas: Predicted proteins in FASTA format.
  - tsv: Predictions in tabular format.
params:
  - extra: Additional non-file arguments to pass to MetaEuk (e.g., --e-value, --min-length).
