rule all:
    input:
        "gtdbtk.summary.tsv"

rule testar_gtdbtk:
    input:
        "data"
    output:
        "gtdbtk.summary.tsv"
    params:
        extension="fasta",
        extra=""
    threads: 2
    wrapper:
        "master/bio/gtdb-tk"