rule all:
    input:
        "recognizer_results.tsv"

rule testar_recognizer:
    input:
        fasta="sequences.fasta"
    output:
        "recognizer_results.tsv"
    params:
        resources_dir="recognizer_db",
        extra="--evalue 0.001"
    threads: 1
    wrapper:
        "master/bio/recognizer"