rule all:
    input:
        "reCOGnizer_results.tsv"

rule testar_recognizer:
    input:
        fasta="sequences.fasta"
    output:
        "reCOGnizer_results.tsv"
    params:
        extra="--evalue 0.001"
    threads: 1
    wrapper:
        "master/bio/recognizer"