name: prokka
description: Rapid prokaryotic genome annotation.
authors:
  - Rodolfo Brandão Dias Ferreira
  - Artur Rafael de Oliveira Gomes
input:
  - fasta: FASTA file with contigs to annotate.
  - proteins: (Optional) FASTA file of trusted proteins to first annotate from.
output:
  - gff: Standard GFF3 format annotation.
  - faa: Protein FASTA file of the translated CDS sequences.
  - (lista os outros outputs importantes que tens)
params:
  - extra: Additional arguments to pass to Prokka (e.g., --kingdom, --genus, --strain).