rule all:
    input:
        "genome.gff3",
        "genome.faa",
        "genome.tsv"

rule testar_bakta:
    input:
        fasta="contigs.fasta"
    output:
        "genome.gff3",
        "genome.faa",
        "genome.tsv"
    params:
        extra=""
    threads: 1
    wrapper:
        "master/bio/bakta"