rule test_metaeuk:
    input:
        fasta="contigs.fasta",  
        db="db.fasta"
    output:
        fas="resultados.fas"  
    params:
        extra=""             
    threads: 1
    wrapper:
        "master/bio/metaeuk"