rule test_prokka:
    input:
        fasta="genome.fasta"
    output:
        gff="teste_final.gff",
        faa="teste_final.faa"
    params:
        extra=""
    threads: 1
    wrapper:
        "master/bio/prokka"