rule test_prokka:
    input:
        fasta="genome.fasta"
    output:
        gff="results/teste_final.gff",
        faa="results/teste_final.faa"
    params:
        extra=""
    threads: 1
    wrapper:
        "file://../"